### ISSUE TITLE
apply to be an official student organization?

### ISSUE THREAD

**Issue by nicholasjhorton** [RLadies-Amherst/RLadies-Amherst#2]
@nicholasjhorton is glad to serve as faculty advisor

**Comment by aboskovic21** [comment]
Do you know how I can go about starting this process?

**Comment by nicholasjhorton** [comment]
https://www.amherst.edu/campuslife/aas/budgetary/fundingprocess/funding-eligibility/clubs-and-club-recognition?shib_redir=1129959

**Comment by aboskovic21** [comment]
Just a quick update on this front: Jess submitted the form last week!
